# Generated by Django 2.1.3 on 2018-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MalhaLogistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ponto_inicial', models.CharField(max_length=1)),
                ('pronto_final', models.CharField(max_length=1)),
                ('distancia', models.IntegerField()),
            ],
        ),
    ]
