# Generated by Django 2.1.3 on 2018-11-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MalhaLogistica',
            new_name='Logistica',
        ),
        migrations.RenameField(
            model_name='logistica',
            old_name='pronto_final',
            new_name='ponto_final',
        ),
    ]
