# Generated by Django 2.1.3 on 2018-11-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181123_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_inicial', models.CharField(max_length=1)),
                ('ponto_final', models.CharField(max_length=1)),
                ('distancia', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Logistica',
        ),
    ]
